
server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true


spring:
  profiles:
    active: es,swagger,redis,mongo, rabitmq
  datasource:
    url: jdbc:postgresql://52.78.159.20:5432/snoop
    username: ENC(JIxLlHeC+6u59PjTWidzjw==)
    password: ENC(uYYlHgHg5hh6vRr84SVLcEm7kq66Dw0A)
    driver-class-name: org.postgresql.Driver
#    url : jdbc:h2:tcp://localhost/~/snooping
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver



  mail:
    host: smtp.gmail.com
    port: 587
    username: ENC(m6MbBpmIJAK2qG+ZRXPWUegfDJw/qRcy7bSqpZgOC7g=)
    password:
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

  main:
    allow-circular-references: true

  jpa:
    hibernate:
      ddl-auto: update #create update none
    show-sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true

jwt:
  password: ENC(EkScQq/G1fRkMjzEBuJm2929lWSio0h2SP4muyxM5dLQVAMlFLOV5rst66cGRjLTVo6hgqDDcNmzXMegiy6oWj7j8jF8pPX49p6vsWOmgo281iBPdk6kJnhW+mBZ+GN/wd6Vu8twkvKz5pz/PSnpB7/3FN+Et6tKBwZ4OcmQREIoQ5U0m1cJFB2MF/aZwiMfLeLkF7HBRtmlFnUiNKTc80dsFXwkacE6ZMg2QDktra8FI8XNECFhBKEnIWs4pvta82wtMafWl6k=)
  atk: 86400000 # 24 * 60 * 60 * 1000L; 밀리초로 계산한 값
  rtk: 2592000000 # 30 * 24 * 60 * 60 * 1000L; 밀리초로 계산한 값


cloud:
  aws:
    s3:
      bucket: ENC(j2Vberu2AjM0Gwv1yBLsUh5DSPHIM/HL)
    credentials:
      accessKey: ENC(kG422CFkeWJAZ67le7L6jFT0gRgdxBrFPAPe5L2pMi4=)
      secretKey: ENC(nNSf994isGR1HVsPL0fuV8BBWOAmRVN7l7IgJaA6OjKB1qINqUhf/jWuix8UrTkbKFMjkogno+A=)
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false
    cloud:
      url: ENC(1p4FwzESBl2nkhJiVMzdvFh72BRH12yUR162l7j8tJ4areYpQVkIRUEkKSJNgwpg)