
server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true


spring:
  redis:
    host: localhost
    port: 6379

  mail:
    host: smtp.gmail.com
    port: 587
    username: k4minseung@gmail.com
    password: jjeqtheoxnqsigvg
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

  datasource:
    url: jdbc:postgresql://52.78.159.20:5432/snoop
    username: admin
    password: d104d104
    driver-class-name: org.postgresql.Driver
#    url : jdbc:h2:tcp://localhost/~/snooping
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
  main:
    allow-circular-references: true

  profiles:
    active: es
    include: db

  jpa:
    hibernate:
      ddl-auto: update #create update none
    show-sql: true
    properties:
      hibernate:
        show_sql: false
        format_sql: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match:
    - /api/**

jwt:
  password: appaanjanda!appaanjanda!appaanjanda!appaanjanda!hhwehweertappaanjanda!appaanjanda!appaanjanda!appaanjanda!
  atk: 86400000 # 24 * 60 * 60 * 1000L; 밀리초로 계산한 값
  rtk: 2592000000 # 30 * 24 * 60 * 60 * 1000L; 밀리초로 계산한 값
