
server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true


spring:
  redis:
    host: localhost
    port: 6379

  mail:
    host: smtp.gmail.com
    port: 587
    username: k4minseung@gmail.com
    password: jjeqtheoxnqsigvg
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

  datasource:
#    url: jdbc:h2:tcp://localhost/~/shinhan
    url : jdbc:h2:tcp://localhost/~/snooping
    username: sa
    password:
    driver-class-name: org.h2.Driver
  main:
    allow-circular-references: true

  profiles:
    include: db

  jpa:
    hibernate:
      ddl-auto: create #create update none
    show-sql: true
    properties:
      hibernate:
        show_sql: false
        format_sql: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match:
    - /api/**

jwt:
  password: appaanjanda!appaanjanda!appaanjanda!appaanjanda!hhwehweertappaanjanda!appaanjanda!appaanjanda!appaanjanda!
  atk: 86400000 # 24 * 60 * 60 * 1000L; 밀리초로 계산한 값
  rtk: 2592000000 # 30 * 24 * 60 * 60 * 1000L; 밀리초로 계산한 값


#cloud:
#  aws:
#    s3:
#      bucket: ENC(f+pRtzHFinJoboi00ELAXPKKSGyPo9WE)
#    credentials:
#      access-key: ENC(gM+eVGXbg4N0VTlBAA0thgpCZzsfIk3FhvhO1R4jgkg=)
#      secret-key: ENC(AgB9NPKiGb0yXaKLJLu9/lQW/UMG8TvUhHC6thBgUQurIlbvUA79rQIiR0vY177ZSpHmGSI1m2M=)
#    region:
#      static: ap-northeast-2
#      auto: false
#    stack:
#      auto: false
#    cloudfront:
#      url: d3byqpylj7jy1e.cloudfront.net